# le yml permet d'utiliser des images venues d'ailleurs,
# ou des conçues par nous-même grâce à des fichiers Dockerfile
version: "3"

services:
  # Service centrale et unique d'authentification (SSO)
  sso-server:
    # image: node:18
    # plutot qu'utiliser une image node:18 "simple"
    # On va la créer à la main dans notre dossier server
    build: server
    # OU build: server/Dockerfile

    # J'ai besoin de relié le port 80 (défaut) de ma machine hote
    # vers le port 3000 de mon container
    # Sauf que la config de Nginx ne nous permet pas l'écriture classique:
    # ports:
    #   - "80:3000"

    environment:
      VIRTUAL_HOST: sso-server.test
      # Avec l'image Nginx que j'utilise je dois écrire :
      VIRTUAL_PORT: 3000

    # Si je modifie la partie server sur ma machine hote
    # Le volume va permettre de mettre à jour les fichiers dans le container
    # Attention : le volume va écraser les commandes du Dockerfile
    # Car la partie ./server va complétement remplacer ce qui a été fait avant
    # Si je supprime le dossier "nodes_modules" sur ma machine
    # le programme dans le container n'aura plus ce dossier non plus (même avec le npm i)
    volumes:
      - ./server/:/home/node/app

  # Quelques services (sites web) "clients" du SSO
  sso-client1:
    build: client1
    environment:
      VIRTUAL_HOST: sso-client1.test
      VIRTUAL_PORT: 3000
    volumes:
      - ./client1/:/home/node/app

  adminer:
    image: adminer:4.8.1
    environment:
      VIRTUAL_HOST: adminer.test

  whoami:
    image: jwilder/whoami
    environment:
      VIRTUAL_HOST: whoami.test

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
