# Dans ce Dockerfile, je vais pouvoir dérouler toute la logique pour installer mon service
# FROM = image de base (provenant de Dockerhub)
FROM node:18

# Commandes exécutées dans le container
RUN npm install
# Pour créer notre app, on a préféré exécuté npm init -y directement dans le dossier "server"

